language: node_js
node_js:
  - '5.5'

branches:
  only:
    - master

before_install:
  - npm install -g gulp-cli
  - npm install -g mocha

install: npm install

before_script: gulp build

notifications:
  email: false
